#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for src/backend/autoindex
#
# Portions Copyright (c) 1996-2026, PostgreSQL Global Development Group
# Portions Copyright (c) 1994, Regents of the University of California
#
# src/backend/autoindex/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/autoindex
top_builddir = ../../..
include $(top_builddir)/src/Makefile.global

OBJS = \
	autoindex.o \
	index_advisor.o \
	index_lifecycle.o \
	workload_capture.o

include $(top_srcdir)/src/backend/common.mk
